set -g default-terminal screen-256color

setw -g mode-keys vi
set -sg escape-time 0
set -g mouse on

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind -n S-Pageup copy-mode -u
bind -n S-Pagedown copy-mode -u

set -g status-bg colour28
set -g status-fg colour232
set -g status-right "'#H' %H:%M %d-%b-%Y"
