set -g default-terminal "${TERM}"
set -sg escape-time 0

unbind c-b
set -g prefix c-space
bind c-space send-prefix

bind r source-file ~/.tmux.conf
set -g base-index 1

setw -g mode-keys vi
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel
bind -T copy-mode-vi c-v send-keys -X rectangle-toggle

set -g history-limit 10000
set -g mouse on

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

set -g focus-events on

bind c new-window -c "#{pane_current_path}"
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

bind -r H resize-pane -L
bind -r J resize-pane -D
bind -r K resize-pane -U
bind -r L resize-pane -R
