set -sg escape-time 0
setw -g mode-keys vi
set -g status-keys vi
set -g mouse on
set -g focus-events on
set -g history-limit 10000

bind c new-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"
