#!/bin/bash
set -euo pipefail

link() {
    mkdir -p "$(dirname "$2")"
    if [ -e "$2" ]; then
        echo "file $2 already exists."
        rm -f "$2"
    fi
    ln -sf "$1" "$2"
    echo "creating symlinking $1 to $2."
}

curl -L -O https://raw.githubusercontent.com/ifdiego/dotfiles/refs/heads/master/packages
cat ./packages | sudo pacman -S --needed --noconfirm -

git clone https://aur.archlinux.org/yay-bin.git
cd yay-bin
makepkg -si
yay -S brave-bin

git clone https://github.com/ifdiego/dotfiles.git ~/dotfiles
# stow -d ~/dotfiles -t ~ .

link ~/dotfiles/bin ~/.local/bin
chmod +x ~/.local/bin/*

link ~/dotfiles/fish/config.fish ~/.config/fish/config.fish
link ~/dotfiles/ghostty/config ~/.config/ghostty/config
link ~/dotfiles/git/config ~/.config/git/config
link ~/dotfiles/ssh/config ~/.ssh/config

link ~/dotfiles/nvim/init.lua ~/.config/nvim/init.lua
link ~/dotfiles/nvim/lazy-lock.json ~/.config/nvim/lazy-lock.json
nvim --headless "+Lazy! sync" +qa &>/dev/null

link ~/dotfiles/tmux/tmux.conf ~/.config/tmux/tmux.conf
tmux source ~/.config/tmux/tmux.conf

link ~/dotfiles/.editorconfig ~/.editorconfig
link ~/dotfiles/.xprofile ~/.xprofile

sudo cp ~/dotfiles/udevmon.yaml /etc/udevmon.yaml
sudo cp ~/dotfiles/udevmon.service /etc/systemd/system/udevmon.service
sudo systemctl enable --now udevmon.service

chsh -s $(which fish)

rustup default stable
gh auth login

sudo systemctl start docker.service
sudo systemctl enable docker.service
sudo usermod -aG docker "$USER"

gsettings set org.gnome.desktop.input-sources xkb-options "['ctrl:nocaps']"
gsettings set org.gnome.desktop.peripherals.keyboard delay 200
gsettings set org.gnome.desktop.peripherals.keyboard repeat-interval 10

git -C ~/dotfiles remote set-url origin git@github.com:ifdiego/dotfiles.git
