# enforce 256 colors
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

set -sg escape-time 0
setw -g mode-keys vi
set -g status-keys vi
set -g mouse on
set -g focus-events on
set -g history-limit 100000
set -g set-clipboard on
set -g status-interval 1
set -g renumber-windows on
set -g base-index 1

# split commands to use current path
bind c new-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"

# moving between panes with vim movement keys
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# resize panes with vim momement keys
bind -r H resize-pane -L
bind -r J resize-pane -D
bind -r K resize-pane -U
bind -r L resize-pane -R

set -g window-status-current-style bold
