set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",xterm-256color:Tc"
set -sg escape-time 0

unbind c-b
set -g prefix c-a
bind c-a send-prefix

setw -g mode-keys vi
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'
bind -T copy-mode-vi c-v send-keys -X rectangle-toggle

set -g history-limit 100000
set -g mouse on

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
