set -g default-terminal "xterm-ghostty"
set -sg escape-time 0

bind r source-file ~/.config/tmux/tmux.conf

set -g base-index 1
setw -g pane-base-index 1

setw -g mode-keys vi
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi r send-keys -X rectangle-toggle
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel

set -g history-limit 100000
set -g mouse on
set -g focus-events on

bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R

set -g set-titles on
set -g set-titles-string "#T"

bind c new-window -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
