live_config_reload = true
import = ["~/.config/alacritty/theme.toml"]

[env]
TERM = "xterm-256color"

[window]
dynamic_padding = true

[scrolling]
history = 100000

[font]
size = 7.5
offset = { x = 0, y = 1 }

[font.normal]
family = "Hack"

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true

[[hints.enabled]]
regex = """(ipfs:|ipns:|magent:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)\
    [^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"""
hyperlinks = true
command = "xdg-open"
post_processing = true
mouse.enabled = true
