live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
dynamic_padding = true

[scrolling]
history = 100000

[font]
size = 7.5
offset = { x = 0, y = 1 }

[colors.primary]
background = '0x0e1415'
foreground = '0xcecece'

[colors.cursor]
text = '0x0e1415'
cursor = '0xcecece'

[colors.normal]
black = '0x0e1415'
red = '0xe25d56'
green = '0x73ca50'
yellow = '0xe9bf57'
blue = '0x4a88e4'
magenta = '0x915caf'
cyan = '0x23acdd'
white = '0xf0f0f0'

[colors.bright]
black = '0x777777'
red = '0xf36868'
green = '0x88db3f'
yellow = '0xf0bf7a'
blue = '0x6f8fdb'
magenta = '0xe987e9'
cyan = '0x4ac9e2'
white = '0xffffff'

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true

[[hints.enabled]]
regex = """(ipfs:|ipns:|magent:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)\
    [^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"""
hyperlinks = true
command = "xdg-open"
post_processing = true
mouse.enabled = true
