[tools]
bat = "latest"
direnv = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
gh = "latest"
go = "latest"
helix = "latest"
make = "latest"
neovim = "latest"
node = "lts"
pnpm = "latest"
ripgrep = "latest"
rust = "latest"
rust-analyzer = "latest"
starship = "latest"
tmux = "latest"
usage = "latest"
yazi = "latest"
zellij = "latest"
zig = "latest"
zls = "latest"
zoxide = "latest"
